export {Dativ} from './Pages/dativ';
export {Akkusativ} from './Pages/akkusativ';
export {Nominativ} from './Pages/nominativ';
export {Genitiv} from './Pages/genitiv';
export {Random} from './Pages/random';
export {Repeat} from './Pages/repeat';
export {Retry} from './Pages/retry';
export {QuestionRender} from './questionRender'
export {Home} from './Pages/home'
export {RightHeader} from './rightHeader'
export {RightHeaderHome} from './rightHeaderHome'
export {Info} from './Pages/info'
export {Settings} from './Pages/settings'
export {LeftHeader} from './leftHeader'